# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20160611_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_Favorite',
            field=models.BooleanField(default=False),
        ),
    ]
