# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 18:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_song_is_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='is_Favorite',
            new_name='is_favorite',
        ),
    ]
